Первая проверка
Anatoly8853/go_final_project_avp pull request #1
Opened 2024-09-26 15:37 UTC by Anatoly8853

2024-09-27 13:52 UTC, dirtymew requested changes
Привет Анатолий

очень хорошая работа - хочется отметить:
 - структуру проекта
 - архитектуру проекта
 - логированние
 - задания со звездочкой
 
Дал коментарии что поправить(тесты падают и ошибки с операциями через фронтенд) и улучшить, нужно еще документацию добавить
описа как запустить протестировать и настроить приложение

2024-09-27 13:52 UTC, dirtymew commented on .github/workflows/go.yml
> +      - name: Run Tests
тут тесты просто так не заработают - я бы убрал этот этап

чтобы они заработали - нужно сначала поднять сервис - в целом в github это можно сделать, но не просто.

2024-09-27 13:52 UTC, dirtymew commented on Dockerfile
> +COPY go.mod .
COPY . . одной команды хватить - все остальные COPY можно убрать

2024-09-27 13:52 UTC, dirtymew commented on Dockerfile
> +RUN GOOS=linux GOARCH=amd64 go build -o /gofinalprojectavp ./cmd/main.go
GOOS=linux GOARCH=amd64 - лучще в ENV определять

2024-09-27 13:52 UTC, dirtymew commented on Dockerfile
> +EXPOSE 7540
а если TODO_PORT поменяется?

2024-09-27 13:52 UTC, dirtymew commented on Dockerfile
> +ENV TODO_DBFILE=/scheduler.db
/scheduler.db - ну как-то не очень в корень по умолчанию - лучше наверное в /app

2024-09-27 13:52 UTC, dirtymew commented on handler/auth.go
> +	"github.com/dgrijalva/jwt-go"
проблемы с импортами по всему проекту

нужно разделить на 2-3 группы - настрой IDE и/или используй go imports

2024-09-27 13:52 UTC, dirtymew commented on handler/auth.go
> +var jwtSecret = []byte("my_secret_key")
кажется тут хардкод  и планировалось использовать TODO_JWT_SECRET

2024-09-27 13:52 UTC, dirtymew commented on handler/handler.go
> +		c.String(http.StatusInternalServerError, "ошибка при отправке ответа")
хмм - мне почему-то кажется что тут уже бесполезно код ответа выставлять и он уже не будет отправлен

2024-09-27 13:52 UTC, dirtymew commented on repository/repository.go
> +		r.app.Log.Debugf("GetTasks res.Err: %s", err)
логировать лучше на каком-то одном уровне логики - а тут я бы рекомендовал ошибку вернуть - если нужно контекста добавить то ошибку можно обернуть

2024-09-27 13:52 UTC, dirtymew commented on repository/repository.go
> +	query := "SELECT id, date, title, comment, repeat FROM scheduler WHERE 1=1"
тут кажется опечатка WHERE 1=1"

2024-09-27 13:52 UTC, dirtymew commented on repository/repository.go
> +	query += " LIMIT ?"
ну тут можно так - но очень уже сложно - ты тут констуируешь запрос по логике

не очень гибкий подход

гораздо проще было просто для разных кейсов запросы написать - да это немного противоречит принципу DRY но дублирование не всегда плохо - если чтобы его избежать нужно усложнять код то лучше продублировать

2024-09-27 13:52 UTC, dirtymew commented on cmd/main.go
> +	repo := repository.NewRepository(db, app)
по архитектурному решению вот еще полезно будет https://medium.com/@shershnev/layered-architecture-implementation-in-golang-6318a72c1e10

2024-09-27 13:52 UTC, dirtymew commented on tests/settings.go
> +var Token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjczODEyMzEsInBhc3N3b3JkX2hhc2giOiIzMTMyMzMzNDM1In0.3uZPTpI9cKBXtQ7uL1jLP6Mo-WQj-W6FDzkLky_ldv8`
у меня тесты падают @Anatoly8853 нужно чтобы проходили

еше проверял работу приложения с фронта - много ошибок - почти ничего не рабтает

2024-10-01 11:29 UTC, dirtymew approved these changes
Анатолий

задание считаю выполненным

поздравляю и желаю удачи

2024-10-01 11:29 UTC, dirtymew commented on handler/auth.go
> +	"github.com/dgrijalva/jwt-go"
@Anatoly8853  вот так примерно должны импорты выглядеть

```
	"fmt"
	"net/http"
	"time"

	"github.com/dgrijalva/jwt-go"
	"github.com/gin-gonic/gin"
```

2024-10-01 11:29 UTC, dirtymew commented on tests/settings.go
> +var Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjc3NDA4MDAsInBhc3N3b3JkX2hhc2giOiIzMTMyMzMzNDM1In0.fWNneIBrCUlJiEp_FC5K8BuLFHlYojf2bfP_hlt4CHc"
@Anatoly8853 с этим токеном тесты не работают

2024-10-01 17:58 UTC, Anatoly8853 commented on tests/settings.go
> +var Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mjc3NDA4MDAsInBhc3N3b3JkX2hhc2giOiIzMTMyMzMzNDM1In0.fWNneIBrCUlJiEp_FC5K8BuLFHlYojf2bfP_hlt4CHc"
А у меня работает перед отправкой проверял, сейчас сгенерировал новый проверил все работает.

2024-10-01 18:50 UTC, merged